CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  barcode TEXT UNIQUE NOT NULL,
  code TEXT UNIQUE NOT NULL,
  price REAL NOT NULL,
  stockQty INTEGER NOT NULL DEFAULT 0,
  imagePath TEXT DEFAULT '',
  isActive INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS sales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paymentType TEXT NOT NULL,
  subtotal REAL NOT NULL,
  paidAmount REAL NOT NULL,
  changeAmount REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS sale_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  saleId INTEGER NOT NULL,
  productId INTEGER NOT NULL,
  qty INTEGER NOT NULL,
  unitPrice REAL NOT NULL,
  lineTotal REAL NOT NULL,
  FOREIGN KEY (saleId) REFERENCES sales(id),
  FOREIGN KEY (productId) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  productId INTEGER NOT NULL,
  type TEXT NOT NULL,
  qty INTEGER NOT NULL,
  note TEXT DEFAULT '',
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (productId) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS closures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  closureDate TEXT NOT NULL,
  totalSalesCount INTEGER NOT NULL,
  cashTotal REAL NOT NULL,
  cardTotal REAL NOT NULL,
  grossRevenue REAL NOT NULL,
  reportPath TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  closureTime TEXT NOT NULL DEFAULT '23:00',
  lowStockThreshold INTEGER NOT NULL DEFAULT 10
);

INSERT OR IGNORE INTO settings (id, closureTime, lowStockThreshold) VALUES (1, '23:00', 10);
